[env.development]
name = "family-menu-dev"
compatibility_date = "2024-01-01"

[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-development-secret-key"

[[env.development.d1_databases]]
binding = "DB"
database_name = "family-menu-dev"
database_id = "f0e71d09-6374-4856-858f-bd52a130bd2d"

[env.production]
name = "family-menu"
compatibility_date = "2024-01-01"

[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-production-secret-key"

[[env.production.d1_databases]]
binding = "DB"
database_name = "family-menu"
database_id = "72015ae1-bde3-47d2-b29b-83ecba66b701"
